dashboard/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :studies do
    resources :graphs, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :graphs
  resources :studies

  get '/about', to: 'about#index'

  # Defines the root path route ("/")
  # root "articles#index"
end

dashboard/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

dashboard/app/models/graph.rb
class Graph < ApplicationRecord
  belongs_to :study
end

dashboard/app/models/study.rb
class Study < ApplicationRecord
  belongs_to :user
  has_many :graphs, dependent: :destroy
end

dashboard/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :studies, dependent: :destroy
end

dashboard/app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    
    end
end

dashboard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

dashboard/app/controllers/graphs_controller.rb
require 'json'
require 'net/http'

class GraphsController < ApplicationController
  before_action :set_graph, only: %i[ show edit update destroy ]
  before_action :set_study
  before_action :check_owner, only: [:edit, :update, :destroy]


  
  @@api = "http://localhost:4567/coordinates"


  # GET /graphs or /graphs.json
  def index
    @graphs = Graph.all
  end

  # GET /graphs/1 or /graphs/1.json
  def show
  end

  # GET /graphs/new
  def new
    @graph = Graph.new
  end

  # GET /graphs/1/edit
  def edit
    @graph = Graph.find(params[:id])
  end



  # begin
  #   graph.coords = get_coordinates_from_api
  #   graph.save!
  # rescue StandardError => e
  #   puts "Error occurred: #{e}"
  #   graph.coords = [{x: 1, y: 2}, {x: 2, y: 5}, {x: 3, y: 6}]
  #   graph.save!
  # end
  
  # def create
  #   @graph = @study.graphs.new(graph_params)
  #   @graph.coords =  JSON.generate [{x: 1, y: 2}, {x: 2, y:5}, {x:3, y:6}]
  #   if @graph.save
  #     # Enqueue the GraphWorker job
  #     GraphWorker.perform_async(@graph.id)
  #     redirect_to study_path(@study), notice: 'Graph was successfully created. Processing coordinates in the background.'
  #   else
  #     format.html { render :new, status: :unprocessable_entity }
  #     format.json { render json: @graph.errors, status: :unprocessable_entity }
  #   end
  # end
  
  
  def create
    @graph = @study.graphs.new(graph_params)
    @graph.save
    begin
    json_graph = @graph.to_json
    uri = URI(@@api)
    res = Net::HTTP.post_form(uri, {'graph' => json_graph})
    @graph.coords = res.body #store the coords as JSON dont parse until display
    @graph.save

    rescue StandardError => error
      @graph.coords = JSON.generate [{x: 1, y: 2}, {x: 2, y:5}, {x:3, y:6}]
      @graph.save!
      flash[:error] = "Error: #{error}. Failed to retrieve coordinates. Please edit and try again."
    end


    if @graph.save
      redirect_to study_path(@study), notice: 'Graph was successfully created.'
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @graph.errors, status: :unprocessable_entity }
    end
  end





  # PATCH/PUT /graphs/1 or /graphs/1.json
  def update
    respond_to do |format|
      if @graph.update(graph_params)
        json_graph = @graph.to_json
        uri = URI(@@api)
        res = Net::HTTP.post_form(uri, {'graph' => json_graph})
        @graph.coords = res.body #store the coords as JSON dont parse until display
        @graph.save

        format.html { redirect_to study_url(@study), notice: "Graph was successfully updated." }
        format.json { render :show, status: :ok, location: @graph }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphs/1 or /graphs/1.json
  def destroy
    @graph.destroy

    respond_to do |format|
      format.html { redirect_to graphs_url, notice: "Graph was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def check_owner
      @graph = Graph.find(params[:id])
      unless current_user == @graph.study.user
        redirect_to studies_path, alert: "You are not authorized to perform this action."
      end
    end
  
  # Use callbacks to share common setup or constraints between actions.
    def set_graph
      @graph = Graph.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def graph_params
      params.require(:graph).permit(:name, :description, :start_year, :end_year, :year, :range, :month, :day, :hour, :independent_var, :dependent_var, :chart_type, :category, :location, :lat, :lon, :function, :study_id)
    end
  
    def set_study
      @study = Study.find(params[:study_id])
    end
end

dashboard/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

dashboard/app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: %i[ show edit update destroy ]
  before_action :check_owner, only: [:edit, :update, :destroy]

  # GET /studies or /studies.json
  def index
    @studies = Study.all
  end

  # GET /studies/1 or /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies or /studies.json
  def create
    @study = Study.new(study_params)
    @study.user = current_user
    respond_to do |format|
      if @study.save
        format.html { redirect_to study_url(@study), notice: "Study was successfully created." }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1 or /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to study_url(@study), notice: "Study was successfully updated." }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1 or /studies/1.json
  def destroy
    @study.destroy

    respond_to do |format|
      format.html { redirect_to studies_url, notice: "Study was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def check_owner
      @study = Study.find(params[:id])
      unless current_user == @study.user
        redirect_to studies_path, alert: "You are not authorized to perform this action."
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def study_params
      params.require(:study).permit(:name, :description, :user_id)
    end
end

dashboard/app/helpers/about_helper.rb
module AboutHelper
end

dashboard/app/helpers/application_helper.rb
module ApplicationHelper
end

dashboard/app/helpers/graphs_helper.rb
module GraphsHelper
end

dashboard/app/helpers/home_helper.rb
module HomeHelper
end

dashboard/app/helpers/studies_helper.rb
module StudiesHelper
end

dashboard/app/views/about/index.html.erb
<div class="blocking">

<div class="row">

<div class="col-md-12  d-flex justify-content-center mt-5">


    <h1>About Idaweather.com</h1>

</div>

</div>


<div class="row mt-5">
    <div class="col d-flex justify-content-center mt-5">

    </div>



</div>

<div class="row mb-5">
     <div class="col d-flex justify-content-center mt-5">
        Contact: sam@baremetalnetworks.com

    </div>
</div>

<div class="row mb-5">
    <div class="col d-flex justify-content-center mt-5">
    Disclaimer of Warranties and Limitation of Liability

idaweather.com (the "Website") and its contents, including but not limited to weather forecasts, reports, data, and other information, are provided "AS IS" and "AS AVAILABLE." The owner of the Website, its affiliates, licensors, and service providers make no representations or warranties of any kind, express or implied, as to the operation of the Website or the information, content, or materials included therein.

To the fullest extent permissible by applicable law, the owner of the Website, its affiliates, licensors, and service providers disclaim all warranties, express or implied, including but not limited to, implied warranties of merchantability, fitness for a particular purpose, and non-infringement. The owner of the Website does not warrant that the Website, its content, or the servers hosting the Website are free of viruses or other harmful components.

The owner of the Website, its affiliates, licensors, and service providers shall not be liable for any damages of any kind arising from the use of the Website, including but not limited to, direct, indirect, incidental, punitive, and consequential damages, even if the owner of the Website has been advised of the possibility of such damages.

By using the Website, you expressly agree that your use of the Website is at your sole risk. You agree to assume full responsibility for any and all consequences resulting from your use of the Website and the information contained therein, and you agree to hold the owner of the Website, its affiliates, licensors, and service providers harmless from any claim, loss, or damage that may arise from your use of the Website.

The information provided on the Website is for general informational purposes only and should not be relied upon as a basis for making any decisions, including but not limited to decisions related to travel, outdoor activities, or personal safety. The Website does not guarantee the accuracy, completeness, or timeliness of the information provided, and the owner of the Website shall not be liable for any reliance on such information.

Your use of the Website and any dispute arising out of such use shall be governed by the laws of the jurisdiction in which the owner of the Website is located, without regard to its conflict of law provisions.

    </div>
    </div>






</div>

dashboard/app/views/graphs/_form.html.erb
<div class="container">
<%= form_with(model: graph, url: [@study, graph], class: "needs-validation", novalidate: true) do |form| %>


  <% if graph.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(graph.errors.count, "error") %> prohibited this graph from being saved:</h2>

      <ul>
        <% graph.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row mb-5">
  <div class="col">
    Note: It takes around 60 seconds to process, please allow it time to complete.
  </div>
</div>


  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
    <div class="invalid-feedback">
      Please provide a name for the graph.
    </div>
  </div>

<div class="row">
 <div class="col-6">
    <%= form.label :location, class: "form-label" %>
    <%= form.select :location, ["Buhl",                    
 "Burley",                  
 "Caldwell",                
 "Cour d'Alene",            
 "Emmett",                  
 "Gannet",
 "Gooding",
 "Grangeville",
 "Idaho Falls",
 "Ketchum",
 "Minidoka",
 "Moscow",
 "Mountain Home",
 "Mountains West of Jackpot",
 "Murtaugh",
 "Oakley",
 "Payette",
 "Pike Mountain",
 "Pocatello",
 "Salmon",
 "Twin Falls"] 
 %>
  </div>


  <div class="col-6">
    <%= form.label :dependent_var, class: "form-label" %>
    <%= form.select :dependent_var, [ "temperature",                                                         
 "dewpoint_temperature",                                                
 "soil_temperature_level_1",                                            
 "soil_temperature_level_2",                                            
 "soil_temperature_level_3",                                            
 "soil_temperature_level_4",
 "surface_thermal_radiation",
 "surface_solar_radiation",
 "direct_normal_solar_radiation",
 "surface_diffuse_solar_radiation",
 "relative_humidity",
 "surface_pressure",
 "mean_sea_level_pressure",
 "total_cloud_cover",
 "total_precipitation",
 "snowfall",
 "snow_depth",
 "snow_density",
 "volumetric_soil_water_layer_1",
 "volumetric_soil_water_layer_2",
 "volumetric_soil_water_layer_3",
 "volumetric_soil_water_layer_4",
 "wind_speed",
 "wind_direction",
 "10m_wind_gust",
 "100m_wind_speed",
 "100m_wind_direction"]
         %>
  </div>


</div>




  <div class="mb-3 mt-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

<div class="row">
<div data-controller="form">
  <div class="col">
    <%= form.collection_select :category, ["Range_across_years", "Compare_one_month_across_years", "Monthly_for_one_year", "Hourly_for_one_month_in_a_single_year"],
    :to_s, :titlecase, {}, data: { action: "change->form#toggle" }, id: "foo" %>
  </div>

  <div class="col">

    <div id="startYearField">
      <div data-form-target="startYear">
        <%= form.label "Start Year (1950-2022)" %>
        <%= form.text_field :start_year, class: "form-control", data: { target: "form.startYear" } %>
      </div>
    </div>

    <div id="endYearField">
      <div data-form-target="endYear">
        <%= form.label "End Year (1950-2022)" %>
        <%= form.text_field :end_year, class: "form-control", data: { target: "form.endYear" } %>
      </div>
    </div>

    <div id="yearField">
      <div data-form-target="year">
        <%= form.label "Year (1950-2022)" %>
        <%= form.text_field :year, class: "form-control", data: { target: "form.year" } %>
      </div>
    </div>

    <div id="monthField">
      <div data-form-target="month">
        <%= form.label "Month (1-12)" %>
        <%= form.text_field :month, class: "form-control", data: { target: "form.month" } %>
      </div>
    </div>
  </div>
</div>
</div>






<div class="row mt-5">
<div class="col">
  <%= form.label :function, class: "form-label" %>
  <%= form.select :function, ["mean", "max", "min"], class: "form-select" %>
</div>
</div>

<div class="row mt-1">
<div class="col">
  <%= form.label :chart_type, class: "form-label" %>
  <%= form.select :chart_type, ["line", "scatter", "bar", "area", "pie"], class: "form-select" %>
</div>
</div>











  <div class="row" >
    <div class="col d-flex justify-content-center">
    <%= form.submit "Submit", class: "btn btn-primary mt-3 btn-lg"%>
    </div>
  </div>



<% end %>
</div>

dashboard/app/views/graphs/_graph.html.erb
<div id="<%= dom_id graph %>">
  <p>
    <strong>Name:</strong>
    <%= graph.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= graph.description %>
  </p>

  <p>
    <strong>Start year:</strong>
    <%= graph.start_year %>
  </p>

  <p>
    <strong>End year:</strong>
    <%= graph.end_year %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= graph.year %>
  </p>

  <p>
    <strong>Range:</strong>
    <%= graph.range %>
  </p>

  <p>
    <strong>Month:</strong>
    <%= graph.month %>
  </p>

  <p>
    <strong>Day:</strong>
    <%= graph.day %>
  </p>

  <p>
    <strong>Hour:</strong>
    <%= graph.hour %>
  </p>

  <p>
    <strong>Independent var:</strong>
    <%= graph.independent_var %>
  </p>

  <p>
    <strong>Dependent var:</strong>
    <%= graph.dependent_var %>
  </p>

  <p>
    <strong>Chart type:</strong>
    <%= graph.chart_type %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= graph.category %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= graph.location %>
  </p>

  <p>
    <strong>Lat:</strong>
    <%= graph.lat %>
  </p>

  <p>
    <strong>Lon:</strong>
    <%= graph.lon %>
  </p>

  <p>
    <strong>Function:</strong>
    <%= graph.function %>
  </p>

  <p>
    <strong>Study:</strong>
    <%= graph.study_id %>
  </p>

</div>

dashboard/app/views/graphs/edit.html.erb
<div class="blocking">
<h1>Editing graph</h1>

<%= render "form", graph: @graph %>

<br>

</div>

dashboard/app/views/graphs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Graphs</h1>

<div id="graphs">
  <% @graphs.each do |graph| %>
    <%= render graph %>
    <p>
      <%= link_to "Show this graph", graph %>
    </p>
  <% end %>
</div>

<%= link_to "New graph", new_graph_path %>

dashboard/app/views/graphs/new.html.erb
<div class="blocking">
<h1>New graph</h1>

<%= render "form", graph: @graph %>

<br>


</div>

dashboard/app/views/graphs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @graph %>

<div>
  <%= link_to "Edit this graph", edit_graph_path(@graph) %> |
  <%= link_to "Back to graphs", graphs_path %>

  <%= button_to "Destroy this graph", @graph, method: :delete %>
</div>

dashboard/app/views/home/index.html.erb
<div class="blocking">
<div id="hero">
<div class="row">
<div class="col-12 d-flex justify-content-center mt-5">


<h1 style="margin-bottom: 5rem">Welcome to IdaWeather</h1>
</div>
</div>

</div>



<div class="row mt-3 ">

<div class="col-md-6">
<%= image_tag 'weather-1.jpg', width: '100%' %>
</div>

<div class="col-md-6 mt-4">
<h2>Create Historical Weather Studies</h2>



<div class="mt-4">

<i class="fa-solid fa-magnifying-glass-chart  fa-2xl"></i> Query and run statistics on 13,479,035 weather records.

</div>
<div class="mt-4">

<i class="fa-solid fa-book fa-2xl"></i> Records on 21 locations in Idaho available for every hour (1950-2022)

</div>

<div class="mt-4">

<i class="fa-solid fa-chart-simple fa-2xl"></i> 27 different features, including soil moisture/temperature, solar radiation etc.

</div>


<div class="mt-4">
<i class="fa-solid fa-location-crosshairs fa-2xl"></i> Buhl, Burley, Caldwell, Cour d'Alene, Emmett, Gannet, Gooding, Grangeville, Idaho Falls, Ketchum, Minidoka, Moscow, Mountain Home, Mountains West of Jackpot, Murtaugh, Oakley, Payette, Pike Mountain, Pocatello, Salmon, and Twin Falls.
</div>

</div>

</div>


<div class="row mt-5 ">

  <div class="col-md-6">
<h2>27 Features Available in the Dataset</h2>
<p>The IdaWeather dataset contains 27 different features,
ranging from temperature, pressure, and solar radiation to sub-surface soil temperature and moisture levels.
</p>

<p style="color: red">Note: All values are in metric<p>

<b class=" d-flex justify-content-center mt-5">Features</b>
<ol class="list-group  mt-2">
  <li class="list-group-item">Temperature, Dewpoint Temperature (*C)</li>
  <li class="list-group-item">Soil Temperature Layer 1-4 (*C)</li>
  <li class="list-group-item">Volumetric Soil Water Layer 1-4 (%)</li>
  <li class="list-group-item">Surface [Thermal, Solar, Diffuse] Radiation (W/m^2)</li>
  <li class="list-group-item">Relative Humidity (%)</li>
  <li class="list-group-item">Surface Pressure, Sea Level Pressure (Pascals)</li>

  <li class="list-group-item">Total Cloud Cover (%)</li>
  <li class="list-group-item">Total Precipitation (mm)</li>
  <li class="list-group-item">Snowfall, Snow Depth, Snow Density (mm)</li>

  <li class="list-group-item">Wind Speed, Direction, 10m Gust, 100m Speed & Direction (m/s)</li>

</ol>


<div class="mt-5">
<p>
<b class=" d-flex justify-content-center mt-5">Layer depths (for Soil Temperature and Moisture)</b>
</p>
<ul class="list-group">
  <li class="list-group-item">Layer 1 (0 - 7cm) - (0 - 2.75 inches)</li>
  <li class="list-group-item">Layer 2 (7 - 28cm) - (2.75 - 11 inches)</li>
  <li class="list-group-item">Layer 3 (28 - 100cm) - (11 - 39.4 inches)</li>
  <li class="list-group-item">Layer 4 (100 - 289cm) - (39.4 - 113.4 inches)</li>
</ul>
</div>

</div>

  <div class="col-md-6">
<%= image_tag 'weather-2.jpg', width: '100%' %>
  </div>

</div>




<div class="row mt-5">
  <div class="col-6">

</div>

    <div class="col-6">

</div>

<div class="row mb-5">


</div>

</div>

dashboard/app/views/layouts/_alerts.html.erb
<% if notice %>
<p class="notice flash" color: green"><%= notice %></p>
<% elsif alert %>
<p class="alert flash" style="color: red"><%= alert %></p>
<% end %>

dashboard/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">

<a class="navbar-brand" href="/">IdaWeather</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="/">Home</a>
    </li>
    <li class="nav-item">
      <%= link_to "Explore", studies_path, class: 'nav-link' %>
    </li>

    
    <%= render 'user/session_manager' %>

    <li class="nav-item">
      <%= link_to "About", about_path, class: 'nav-link' %>
    </li>
  </ul>
  <form class="d-flex" role="search">


  </form>
</div>

</nav>

dashboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdaWeather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<div id="container">
  
<header>
<%= render 'layouts/navbar' %>


</header>


  <body>
<div class="container">
    <%= render 'layouts/alerts' %>

    <%= yield %>
</div>
  </body>
 </div>
</html>

dashboard/app/views/studies/_study_toolbar.html.erb
<div class="row">
<div class="col">
<%= link_to '', new_study_graph_path(@study),
        class: "fa-solid fa-chart-line ", title: 'New Graph' %>

<%= link_to "", edit_study_path(@study),
        class: "fa-solid fa-sliders", title: "Edit Study" %> 

<%= link_to "", studies_path,
        class: "fa-solid fa-arrow-left", title: "Back to Studies" %>

<%= link_to "", @study, data: { turbo_method: :delete },
        class: "fa-solid fa-circle-xmark", title: "Delete Study" %>
</div>
</div>

dashboard/app/views/studies/edit.html.erb
<div class="blocking">
<h1>Editing study</h1>

<%= render "form", study: @study %>

<br>

<div>
  <%= link_to "Show this study", @study %> |
  <%= link_to "Back to studies", studies_path %>
</div>
</div>

dashboard/app/views/studies/index.html.erb
<div class="blocking">
<div class="row">
<div class="col d-flex justify-content-center mb-5">
<h1>Studies</h1>

</div>
<%= link_to "New study", new_study_path %>

<div id="studies">
  <% @studies.each do |study| %>
    <div class="row mt-5">
    <%= render study %>


    </div>
  <% end %>
</div>

</div>

dashboard/app/views/studies/new.html.erb
<div class="blocking">

<div class="row">
<div class="col-12">
<h1>New study</h1>

<%= render "form", study: @study %>

<br>
</div>
</div>





<div>
  <%= link_to "Back to studies", studies_path %>
</div>
</div>

dashboard/app/views/studies/show.html.erb
<div class="blocking">
<div class="container">


  <div class="row">
    <div class="col-md-10"></div>
      <div class="col d-flex justify-content-center">
        <%= render 'study_toolbar' %>
      </div>
    </div>
  </div>


  <div class="row mt-5">
    <div class="col-12 d-flex justify-content-center">
      <h1><%= @study.name %></h1>
    </div>
  </div>

  <div class="row mb-5">
    <div class="col d-flex justify-content-center">
      <%= @study.description %>
    </div>
  </div>




  <% if @study.graphs.any? %>
      <% @study.graphs.each do |graph| %>
        <div class="row mt-5">
          <div class="col d-flex justify-content-center ">
              <h2><%= graph.name %></h2>
          </div>
        </div>

        <div class="row">
            <div class="col-12">
              <%= 
              coords = JSON.parse(graph.coords)
              @foo = Vega.lite
                .data(coords)
                .mark(type: graph.chart_type, tooltip: true)
                .encoding(
                  x: {field: "x", type: "nominal"},
                  y: {field: "y", type: "quantitative"}
                )
              %>
          </div>
        </div>

        <div class="row">
          <div class="col-10">
            <i class="fa-solid fa-location-crosshairs"></i> <%= graph.location %>, ID
            <i class="fa-brands fa-wpexplorer"></i> <%= graph.dependent_var.capitalize %>
            <i class="fa-solid fa-square-root-variable"></i> <%= graph.function.capitalize %>
            <i class="fa-solid fa-box-archive"></i> <%= graph.category.truncate(20) %>
          </div>

          <div class="col-2 d-flex justify-content-center">
            <div class="row">
              <div class="col">
            <%= link_to '', edit_study_graph_path(@study, graph),
                 class: "fa-solid fa-sliders", title: "Edit Graph" %>
            <%= link_to "", study_graph_path(@study, graph), data: { turbo_method: :delete },
                 class: "fa-solid fa-circle-xmark", 
                 confirm: "Are you sure?", 
                 title: "Delete Graph" %>
              </div>
            </div>
          </div>
        </div>

        <div class="row mt-3">
          <div class="col-4">

          </div>
        </div>

        <div class="row mt-3">
          <div class="col d-flex justify-content-center ">
            <p><%= graph.description %></p>
          </div>
        </div>
      <% end %>
  
      <% else %>
        <p>No graphs found.</p>

        <%= link_to 'Create a New Graph', new_study_graph_path(@study), title: 'New Graph' %>
    <% end %>


</div>
</div>

dashboard/app/views/user/_session_manager.html.erb
<% if current_user %>
<li class="nav-item">
  <%= link_to "New Study", new_study_path, class: "nav-link" %>

</li>

<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <%= current_user.email %>
  </a>
  <ul class="dropdown-menu">

    <li><hr class="dropdown-divider"></li>
    <li> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
  </ul>
</li>

<% else %>
<li class="nav-item">
  <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
</li>
<li class="nav-item">
  <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
</li>
<% end %>